services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ScalaREST
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./app/models/DBModel.sql:/docker-entrypoint-initdb.d/DBModel.sql
    networks:
      - library-net

  app1:
    build: .
    container_name: library-app1
    restart: on-failure
    depends_on:
      - db
    ports:
      - "9001:9000"
      - "50051:50051"
    networks:
      - library-net

  app2:
    build: .
    container_name: library-app2
    restart: on-failure
    depends_on:
      - db
    ports:
      - "9002:9000"
      - "50052:50051"
    networks:
      - library-net

  app3:
    build: .
    container_name: library-app3
    restart: on-failure
    depends_on:
      - db
    ports:
      - "9003:9000"
      - "50053:50051"
    networks:
      - library-net

volumes:
  db_data:

networks:
  library-net:
    driver: bridge
